- name: Copying the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: installing {{COMPONENT}}
  ansible.builtin.package:
      name: mongodb-org
      state: present

- name: Starting {{COMPONENT}}
  systemd:
    name: mongod
    state: restarted 
    enabled: yes

- name: Configuring Service name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}